version: '3'
services:
  fileserver:
    image: fileserver
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    command: python -m flask run --host 0.0.0.0
    ports:
      - "$SERVER_PORT:5000"
    volumes:
      - files:/var/www/files
    env_file:
      - .env

volumes:
  files: